version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./infra/Dockerfile
      target: dev
    container_name: stats_vis_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    command: symfony serve --port=8000 --allow-all-ip --no-tls
