apiVersion: v1
kind: Service
metadata:
  name: stats-visualiser-nginx-service
spec:
  selector:
    app: stats-visualiser-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
